// Re-export all components from Transform.ts (which now contains all components)
export {
  Position,
  Velocity,
  Rotation,
  Scale,
  SpriteComponent,
  AnimationComponent,
  Collider,
  RigidBody,
  Health,
  Damage,
  PlayerControlled,
  Vehicle,
  Pedestrian,
  Driver,
  VehicleOccupants,
  VehiclePhysics,
  PedestrianAI,
  PedestrianState,
  TrafficAI,
  TrafficState,
  allComponents,
} from './Transform.js';
